package lexer

var (
	EQUAL = "="
	OPEN_PARENTHESIS = "("
	CLOSE_PARENTHESIS = ")"
	OPEN_CURLY = "{"
	CLOSE_CURLY = "}"
	SEMICOLON = ";"
	PLUS = "+"
	MINUS = "-"
	MULTIPLY = "*"
	DIVIDE = "/"
	MODULO = "%"

	SEPERATOR = SEMICOLON
	SCOPE_START = OPEN_CURLY
	SCOPE_END = CLOSE_CURLY
)
